print("汉化脚本 v3.3")

-- ===== 精确翻译表（整句完全匹配）=====
-- 请在此按 ["英文原文"] = "中文翻译" 格式添加
local Translations = {
    -- 示例: ["Home"] = "主页",
    ["+50% Plot Item Capacity"] = "+50% 地块物品容量",
    ["+50% Selling Space"] = "+50% 销售空间",
    
    ["9mm Bullets"] = "9毫米子弹",
    ["Accent color"] = "强调色",
    ["Accessories"] = "配件",
    ["Accessory Loadout Before Auction"] = "拍卖前配件装载",
    ["Accessory Loadout Before Grade Collection"] = "评级收集前配件装载",
    ["Accessory Loadout Before Luck Drink"] = "幸运饮料前配件装载",
    ["Account"] = "账户",
    ["Acid"] = "酸蚀",
    ["Acoustic Guitar"] = "原声吉他",
    ["Advertising"] = "广告",
    ["Aggressive (edge lock)"] = "激进（边缘锁定）",
    ["Air Conditioner"] = "空调",
    ["Air Intake"] = "空气摄入量",
    ["Air Purifier"] = "空气净化器",
    ["Airforce Dominus"] = "空军多米纳斯",
    ["Also Sell Items In Truck"] = "也出售卡车中的物品",
    ["Always Grab Mutated Loot"] = "总是拿变异战利品",
    ["an admin script dedicated to provide the necessities of exploiting."] = "一个致力于提供作弊必备功能的管理脚本。",
    ["Anchor Monument"] = "锚固纪念碑",
    ["Ancient"] = "古代",
    ["Angklung"] = "昂格伦古",
    ["Animal Cage"] = "动物笼子",
    ["Anti Gameplay Pause"] = "反游戏暂停",
    ["Anti Rejoin"] = "反重新加入",
    ["Anti-AFK"] = "反挂机",
    ["Antique"] = "古董",
    ["Any"] = "任何",
    ["Any Selected Mutation"] = "任何选中的变异",
    ["Apple Seeds"] = "苹果种子",
    ["Apple Tree"] = "苹果树",
    ["Arcade Machine"] = "街机",
    ["Artifact"] = "神器",
    ["ATM"] = "自动取款机",
    ["Auction Areas"] = "拍卖区域",
    ["Auction Garage ESP"] = "拍卖车库 ESP",
    ["Auctions"] = "拍卖",
    ["Authentication"] = "认证",
    ["Auto Accept NPC Offers"] = "自动接受 NPC 报价",
    ["Auto Authenticate Accessories"] = "自动认证配件",
    ["Auto Bid"] = "自动出价",
    ["Auto Bid / Auto Buyout"] = "自动出价 / 自动买断",
    ["Auto Buy + Equip Best Lockpick"] = "自动购买并装备最佳开锁工具",
    ["Auto Buy Luck Energy Drinks"] = "自动购买幸运能量饮料",
    ["Auto Buy Powers"] = "自动购买能力",
    ["Auto Buy Shop Upgrades"] = "自动购买商店升级",
    ["Auto Calculator"] = "自动计算器",
    ["Auto Claim Achievements"] = "自动领取成就",
    ["Auto Claim Auction Winnings"] = "自动领取拍卖收益",
    ["Auto Claim Available Plot"] = "自动领取可用地块",
    ["Auto Claim Collections"] = "自动领取收藏",
    ["Auto Claim Daily Reward"] = "自动领取每日奖励",
    ["Auto Claim Meteor Drops"] = "自动领取流星掉落",
    ["Auto Claim Museum Rewards"] = "自动领取博物馆奖励",
    ["Auto Claim Quest Rewards"] = "自动领取任务奖励",
    ["Auto Collect Finished Items"] = "自动收集完成的物品",
    ["Auto Collect Lost & Found"] = "自动收集失物招领",
    ["Auto Collect World Loot"] = "自动收集世界战利品",
    ["Auto Decline Low Offers"] = "自动拒绝低报价",
    ["Auto Equip Rod"] = "自动装备鱼竿",
    ["Auto Expand Item Capacity"] = "自动扩展物品容量",
    ["Auto Expand Shelf 个槽位"] = "自动扩展货架槽位",
    ["Auto Expand Shop Floor"] = "自动扩展商店地板",
    ["Auto Favorite Accessory Stats"] = "自动收藏配件属性",
    ["Auto Favourite Matching Items"] = "自动收藏匹配物品",
    ["Auto Favourite Trophy Rule"] = "自动收藏奖杯规则",
    ["Auto Feed Uranium"] = "自动喂铀",
    ["Auto Fish"] = "自动钓鱼",
    ["Auto Fishing"] = "自动钓鱼",
    ["Auto Get Quests"] = "自动获取任务",
    ["Auto Grade Items"] = "自动评级物品",
    ["Auto Hire + Upgrade Staff"] = "自动雇佣 + 升级员工",
    ["Auto Install Parts"] = "自动安装零件",
    ["Auto Kick Top Bidder"] = "自动踢出最高出价者",
    ["Auto Loot / Auto Sell"] = "自动拾取 / 自动出售",
    ["Auto Open Safes (Locksmith)"] = "自动打开保险箱（锁匠）",
    ["Auto Picklock All Compatible Safes"] = "自动撬开所有兼容保险箱",
    ["Auto Place Method"] = "自动放置方法",
    ["Auto Place Selected Types On Plot"] = "自动在地块上放置选中类型",
    ["Auto Play"] = "自动游玩",
    ["Auto Quest - Configuration"] = "自动任务 - 配置",
    ["Auto Quest - Control"] = "自动任务 - 控制",
    ["Auto Quest - Live Status"] = "自动任务 - 实时状态",
    ["Auto Reel"] = "自动收线",
    ["Auto Repair Inventory + Winnings With Wrench"] = "用扳手自动修理库存 + 收益",
    ["Auto Repair Items"] = "自动修理物品",
    ["Auto Reprice Existing Stock"] = "自动重新定价现有库存",
    ["Auto Sell"] = "自动出售",
    ["Auto Sell Broken Rods"] = "自动出售损坏鱼竿",
    ["Auto Speed Up Slots"] = "自动加速槽位",
    ["Auto Start Auctions"] = "自动开始拍卖",
    ["Auto Stock Shop Shelves"] = "自动补货商店货架",
    ["Auto Store Selected Items"] = "自动存储选中物品",
    ["Auto Swap Broken Rod"] = "自动更换损坏鱼竿",
    ["Auto Time Capsule"] = "自动时间胶囊",
    ["Auto Unfavorite Luck Drinks"] = "自动取消收藏幸运饮料",
    ["Auto Unload"] = "自动卸载",
    ["Auto Unload Truck When Full"] = "卡车满时自动卸载",
    ["Auto Unlock 个槽位"] = "自动解锁槽位",
    ["Auto Use Luck Energy Drinks"] = "自动使用幸运能量饮料",
    ["Auto Wash Items"] = "自动清洗物品",
    ["Auto Wash Rods"] = "自动清洗鱼竿",
    ["Auto X-Ray"] = "自动 X 射线检测",
    ["Axolotl Backpack"] = "水栖生物背包",
    ["Baby Dino Backpack"] = "恐龙宝宝背包",
    ["Baby Dino Dominus"] = "婴儿恐龙多米纳斯",
    ["Back Alley"] = "后巷",
    ["Background color"] = "背景颜色",
    ["Background Image"] = "背景图片",
    ["Bamboo Fence"] = "竹栅栏",
    ["Bamboo Spoiler"] = "竹制扰流板",
    ["Bamboo Tree"] = "竹子树",
    ["Banana Boat"] = "香蕉船",
    ["Banana Tree"] = "香蕉树",
    ["Bar Speaker"] = "酒吧扬声器",
    ["Barracuda Fish"] = "梭鱼",
    ["Basketball"] = "篮球",
    ["Basketball Ring"] = "篮球架",
    ["Bat"] = "球棒",
    ["Bat Wristband"] = "蝙蝠腕带",
    ["Bath Mat"] = "浴室垫子",
    ["Batteries"] = "电池",
    ["Bazooka Ammo"] = "巴祖卡弹药",
    ["BBQ Grill"] = "烧烤架",
    ["Beach Ball"] = "沙滩球",
    ["Beach Bracelet"] = "沙滩手镯",
    ["Beach Chair"] = "沙滩椅",
    ["Beach Decoration Lamp"] = "沙滩装饰灯",
    ["Beach Flag"] = "沙滩旗帜",
    ["Beach Flag Fence"] = "沙滩旗帜栅栏",
    ["Beach Harp"] = "沙滩竖琴",
    ["Beach Hut"] = "沙滩小屋",
    ["Beach Mat"] = "沙滩垫",
    ["Beach Orb"] = "沙滩球体",
    ["Beach Rug"] = "沙滩毯子",
    ["Beach Shirt"] = "沙滩衬衫",
    ["Beach Shower"] = "沙滩淋浴",
    ["Beach Soccer Goal"] = "沙滩足球球门",
    ["Beach Swing"] = "沙滩秋千",
    ["Beach Telescope"] = "沙滩望远镜",
    ["Beach Tent"] = "沙滩帐篷",
    ["Beach Vendor"] = "海滩摊贩",
    ["Beach Wooden Table"] = "沙滩木桌",
    ["Bean Bag"] = "豆袋",
    ["Beanie"] = "无檐帽",
    ["Bear Cap"] = "熊帽",
    ["Bear Trap"] = "捕熊陷阱",
    ["Bed"] = "床",
    ["Bedside Lamp"] = "床头柜灯",
    ["Beehive"] = "蜂巢",
    ["Bench Press"] = "卧推",
    ["Bid Delay"] = "出价延迟",
    ["Bid Only for Needed Parts"] = "仅为需要的零件出价",
    ["Bird House"] = "鸟屋",
    ["Black"] = "黑色",
    ["Blender"] = "搅拌机",
    ["Bling Bracelet"] = "闪亮的手镯",
    ["Blower"] = "吹风机",
    ["Blu-ray Player"] = "蓝光播放器",
    ["Blue Tang Fish"] = "蓝色唐鱼",
    ["Bluetooth Speaker"] = "蓝牙扬声器",
    ["Boat Engine"] = "船用引擎",
    ["Boat Fender"] = "船只护板",
    ["Boat Gearbox"] = "船用齿轮箱",
    ["Boat Winch"] = "船只绞盘",
    ["Bone Backpack"] = "骨头背包",
    ["Bone Dominus"] = "骨头多米纳斯",
    ["Bongo"] = "邦戈鼓",
    ["Bonsai"] = "盆栽",
    ["Book"] = "书",
    ["Boots"] = "靴子",
    ["Bottle"] = "瓶子",
    ["Bottle of Milk"] = "一瓶牛奶",
    ["Bottle Tray"] = "瓶子托盘",
    ["Branding Iron"] = "烙印铁",
    ["Bread Toaster"] = "面包烤面机",
    ["Brick Wall"] = "砖墙",
    ["Broccoli"] = "西兰花",
    ["Broken"] = "损坏",
    ["Bucket"] = "水桶",
    ["Bush"] = "灌木丛",
    ["Butter Churn"] = "奶油搅拌器",
    ["Butter Fish"] = "黄油鱼",
    ["Butterfly Fish"] = "蝴蝶鱼",
    ["Buy When Below"] = "低于时购买",
    ["Bypass Categories"] = "绕过类别",
    ["Bypass Items"] = "绕过物品",
    ["Bypass Mutations"] = "绕过变异",
    ["Bypass Rarities"] = "绕过稀有度",
    ["C4 Wristband"] = "C4腕带",
    ["Cactus"] = "仙人掌",
    ["Cafe Chair"] = "咖啡厅椅子",
    ["Cafe Table"] = "咖啡厅桌子",
    ["Calculator"] = "计算器",
    ["Calung"] = "卡伦格",
    ["Camera"] = "相机",
    ["Camping Backpack"] = "露营背包",
    ["Candle Stand"] = "蜡烛架",
    ["Capsule: Min Item Value ($)"] = "胶囊：最低物品价值 ($)",
    ["Capsule: Only Mutations (empty = all)"] = "胶囊：仅变异（空 = 全部）",
    ["Capsule: Place Min Rarity"] = "胶囊：放置最低稀有度",
    ["Captain Hat"] = "船长帽",
    ["Capybara"] = "卡皮巴拉",
    ["Car Battery"] = "汽车电池",
    ["Car Key"] = "汽车钥匙",
    ["Carbon Fishing Rod"] = "碳素钓鱼竿",
    ["Cardboard Backpack"] = "纸板背包",
    ["Cardboard Hat"] = "纸板帽",
    ["Cargo Car Parts Box"] = "货车零件盒",
    ["Cargo Ship"] = "货船",
    ["Carp Fish"] = "鲤鱼",
    ["Carrot"] = "胡萝卜",
    ["Carryable ESP"] = "可携带物 ESP",
    ["Cash Register"] = "收银台",
    ["Casino Chip"] = "赌场筹码",
    ["Cast Position"] = "抛竿位置",
    ["Caustic"] = "腐蚀",
    ["Caution Bar"] = "警告栏",
    ["Caveman Backpack"] = "穴居人背包",
    ["Caveman Stone Watch"] = "穴居人石头手表",
    ["Ceiling Fan"] = "吊扇",
    ["Ceiling Neon Lamp"] = "天花板霓虹灯",
    ["CelebritySpawns"] = "名人生成",
    ["Cereal Box"] = "谷物盒",
    ["Chalkboard"] = "黑板",
    ["Check out this script!"] = "看看这个脚本！",
    ["Check Vehicle Spawned"] = "检查车辆已生成",
    ["Checker Tile"] = "棋盘地砖",
    ["Cheese Press"] = "奶酪压榨机",
    ["Cheese Slice"] = "奶酪片",
    ["Cheeseburger"] = "芝士汉堡",
    ["Chicken"] = "鸡",
    ["Chicken Coop"] = "鸡舍",
    ["Chicken Egg"] = "鸡蛋",
    ["Chicken Feeder"] = "鸡饲料槽",
    ["Chrome"] = "镀铬",
    ["Chrome, Void"] = "镀铬, 虚空",
    ["Circular Saw"] = "圆锯",
    ["City Bin"] = "城市垃圾桶",
    ["Claim Categories (empty = all)"] = "领取类别（空 = 全部）",
    ["Classic Phone"] = "经典款手机",
    ["Classic Race Car"] = "经典赛车",
    ["Claw Machine"] = "爪子机器",
    ["Clay Pot"] = "黏土罐子",
    ["CLEAR"] = "清除",
    ["Cleaver"] = "切割者",
    ["Client status information"] = "客户端状态信息",
    ["Clothes Hanger"] = "衣架",
    ["Clothes Stand"] = "衣服架",
    ["Cobwebbed"] = "布满蜘蛛网",
    ["Code"] = "代码",
    ["Code Safe"] = "代码保险箱",
    ["Coffee Grinder"] = "咖啡研磨机",
    ["Coffee Machine"] = "咖啡机",
    ["Cold Drink Showcase"] = "冷饮展示柜",
    ["Collection Index"] = "收藏图鉴",
    ["Combine Harvester"] = "联合收割机",
    ["Compass Wristband"] = "指南针腕带",
    ["Compatibility"] = "兼容性",
    ["Competition Gate"] = "比赛大门",
    ["Computer Chip"] = "电脑芯片",
    ["Concrete Fence"] = "混凝土地栅栏",
    ["Config list"] = "配置列表",
    ["Config name"] = "配置名称",
    ["Configuration"] = "配置",
    ["Confirm Min Bid"] = "确认最低出价",
    ["Conga"] = "康佳",
    ["Consistent (Slightly S..."] = "一致（稍慢）...",
    ["Consistent (Slightly Slower)"] = "一致（稍慢）",
    ["Construction Caution Sign"] = "施工警告标志",
    ["Containers (overrides Area)"] = "容器（覆盖区域）",
    ["Conveyor Belt"] = "传送带",
    ["Copy Discord Invite"] = "复制 Discord 邀请",
    ["Copy join script (Job ID)"] = "复制加入脚本 (Job ID)",
    ["Corals"] = "珊瑚",
    ["Corn Plant"] = "玉米植物",
    ["Corn Seeds"] = "玉米种子",
    ["Corn Sheller"] = "玉米脱壳机",
    ["Corner Jacuzzi"] = "墙角按摩浴缸",
    ["Corrupted"] = "已损坏",
    ["Cow"] = "牛",
    ["Cow Backpack"] = "牛背包",
    ["Cow Bell"] = "牛铃",
    ["Cow Milker"] = "奶牛挤奶工",
    ["Crab Backpack"] = "螃蟹背包",
    ["Crab Plushy"] = "螃蟹毛绒玩具",
    ["Crab Trap"] = "螃蟹陷阱",
    ["Cracked Street Lamp"] = "破裂的街灯",
    ["Create config"] = "创建配置",
    ["Create theme"] = "创建主题",
    ["Crowbar"] = "撬棍",
    ["Cruise Ship"] = "游轮",
    ["Crystal Asteroid"] = "水晶小行星",
    ["Crystal Chandelier"] = "水晶吊灯",
    ["Crystal Fence"] = "水晶栅栏",
    ["Crystal Quartz"] = "水晶石英",
    ["Crystal Tower"] = "水晶塔",
    ["Crystal Tubes Decoration"] = "水晶管装饰",
    ["Cucumber"] = "黄瓜",
    ["Current autoload config: none"] = "当前自动加载配置：无",
    ["Current default theme: Monochrome"] = "当前默认主题：单色",
    ["Curved TV"] = "曲面电视机",
    ["Custom theme name"] = "自定义主题名称",
    ["Custom themes"] = "自定义主题",
    ["Customers"] = "顾客",
    ["Dart"] = "飞镖",
    ["Decoration"] = "装饰",
    ["Decoration Lamp"] = "装饰灯",
    ["Deep Fryer"] = "深油炸锅",
    ["Deep Sea Blue Jewel"] = "深海蓝宝石",
    ["Delay After Win"] = "获胜后延迟",
    ["Delay Auctions After Winning"] = "获胜后延迟拍卖",
    ["Delete config"] = "删除配置",
    ["Delete Containers"] = "删除容器",
    ["Delete NPCs"] = "删除 NPC",
    ["Delete theme"] = "删除主题",
    ["Delete Trees"] = "删除树木",
    ["Deselect All"] = "取消全选",
    ["Designer Summer Bag"] = "设计师夏季包",
    ["Devil Faced Face Fish"] = "恶魔脸部鱼",
    ["Diagonal Vent Pipe"] = "斜角通风管",
    ["Diamond"] = "钻石",
    ["Diamond Safe"] = "钻石保险箱",
    ["Diamond Vault"] = "钻石宝库",
    ["Digital Alarm Clock"] = "数字闹钟",
    ["Digital Pet Device"] = "数字宠物设备",
    ["Dino Shell Bracelet"] = "恐龙壳手镯",
    ["Dirty"] = "脏的",
    ["Disabled"] = "禁用",
    ["Disc"] = "光盘",
    ["Display Highlighter"] = "显示高亮器",
    ["Diving Helm"] = "潜水头盔",
    ["Diving Propeller"] = "潜水螺旋桨",
    ["Diving Regulator"] = "潜水调节器",
    ["Djembe"] = "杰姆贝鼓",
    ["Dolphin Statue"] = "海豚雕像",
    ["Donkey"] = "驴子",
    ["Double Barrel"] = "双管炮",
    ["Double Door Refrigerator"] = "双门冰箱",
    ["Double Sofa"] = "双人沙发",
    ["Dresser"] = "梳妆台",
    ["Drink Use Method"] = "饮料使用方法",
    ["Drinks"] = "饮料",
    ["Drinks To Buy (empty = all)"] = "要购买的饮料（空 = 全部）",
    ["Drinks To Use (empty = all)"] = "要使用的饮料（空 = 全部）",
    ["Drone"] = "无人机",
    ["Duck Valk"] = "鸭子飞行员",
    ["Dumbbell"] = "哑铃",
    ["Dumpster"] = "垃圾桶",
    ["Dune"] = "沙丘",
    ["Egg Basket"] = "鸡蛋篮子",
    ["Egg Incubator"] = "蛋孵化器",
    ["Eggplant"] = "茄子",
    ["Elbow Vent Pipe"] = "肘部通风管",
    ["Electric Fan"] = "电扇",
    ["Electric Kettle"] = "电水壶",
    ["Electric Massage Chair"] = "电动按摩椅",
    ["Electric Popcorn Maker"] = "电动爆米花制作机",
    ["Electric Stove"] = "电灶",
    ["Electrical Fedora"] = "电力费多拉帽",
    ["Electronics"] = "电子产品",
    ["Elegant Ceiling Lamp"] = "优雅的吊灯",
    ["Enable Auto Index Completion"] = "启用自动图鉴完成",
    ["Enable Auto Quest Engine"] = "启用自动任务引擎",
    ["Enable Threshold Bypass"] = "启用阈值绕过",
    ["Enter Sign"] = "输入标志",
    ["ESP Max Distance (studs)"] = "ESP 最大距离 (studs)",
    ["ESP Minimum Value ($)"] = "ESP 最低价值 ($)",
    ["EV Car Battery"] = "电动车电池",
    ["EV Charger"] = "电动车充电器",
    ["Every script in the hub is keyless. No key systems, no checkpoints, no linkvertise."] = "中心里的每个脚本都是无密钥的。没有密钥系统，没有检查点，没有 Linkvertise。",
    ["Exclusive"] = "独家",
    ["Exclusives"] = "独家",
    ["EXECUTE"] = "执行",
    ["EXECUTE CLIPBOARD"] = "执行剪贴板",
    ["Exhaust Double Side"] = "双侧排气",
    ["Exit Sign"] = "出口标志",
    ["Expedition Submarine"] = "远征潜艇",
    ["Explorer Backpack"] = "探险家背包",
    ["Explorer Hat"] = "探险家帽",
    ["Export Config to Clipboard"] = "导出配置到剪贴板",
    ["Extra Gavel Trophy"] = "额外的木槌奖杯",
    ["FAQ"] = "常见问题",
    ["Farm Fedora"] = "农场礼帽",
    ["Farm Fence"] = "农场栅栏",
    ["Farm Fence Segment"] = "农场围栏段",
    ["Farm Gate"] = "农场大门",
    ["Farmer Slime"] = "农民粘液",
    ["Farming"] = "刷取",
    ["Farmyard"] = "农场",
    ["Favourites"] = "收藏",
    ["Features"] = "功能",
    ["Feed Troughs"] = "喂食槽",
    ["Fertilized Soil"] = "肥沃的土壤",
    ["Fertilizer Sack"] = "肥料袋",
    ["Fertilizer Spreader"] = "肥料散射器",
    ["Filing Cabinet"] = "文件柜",
    ["Filter Match Mode"] = "过滤器匹配模式",
    ["Filters"] = "过滤器",
    ["Fingerprint Recorder"] = "指纹记录仪",
    ["Fire Pit"] = "火堆",
    ["Firefly"] = "萤火虫",
    ["Firework"] = "烟花",
    ["Fish"] = "鱼",
    ["Fishing"] = "钓鱼",
    ["Fishing Boat"] = "钓鱼船",
    ["Fishing Net"] = "捕鱼网",
    ["Fishing Rod"] = "钓鱼竿",
    ["Flash Grenade"] = "闪光弹",
    ["Flat Screen Monitor"] = "平板屏幕显示器",
    ["Flip Cellphone"] = "翻转手机",
    ["Float Plane"] = "浮动飞机",
    ["Floating Mattress"] = "漂浮的床垫",
    ["Floor Brush"] = "地板刷",
    ["Floor Scrubber"] = "地板擦洗机",
    ["Floor Sign"] = "地板标志",
    ["Floppy Disk"] = "软盘",
    ["Flounder Fish"] = "比目鱼",
    ["Flower Wristband"] = "花朵腕带",
    ["Foldable Mobile Phone"] = "折叠手机",
    ["Folded Table"] = "折叠桌子",
    ["Font color"] = "字体颜色",
    ["Font Face"] = "字体",
    ["Food"] = "食物",
    ["Food Processor"] = "食物加工机",
    ["Footrest"] = "脚架",
    ["Forklift"] = "叉车",
    ["Fossil"] = "化石",
    ["Fossil Valk"] = "化石瓦尔克",
    ["Free Rewards"] = "免费奖励",
    ["Free Vehicle Customisation"] = "免费车辆定制",
    ["Fridge"] = "冰箱",
    ["Frog Throne"] = "青蛙王座",
    ["Fruit Crate"] = "水果箱",
    ["Fruit Skin Helmet"] = "水果皮肤头盔",
    ["Furniture"] = "家具",
    ["Futuristic Sign"] = "未来主义标志",
    ["Game Console"] = "游戏控制台",
    ["Game Info"] = "游戏信息",
    ["Garden Chair"] = "花园椅子",
    ["Garden Fence"] = "花园栅栏",
    ["Garden Hoe"] = "花园锄头",
    ["Garden Rake"] = "花园耙子",
    ["Garden Shovel"] = "花园铲子",
    ["Garden Sundial"] = "花园日晷",
    ["Garden Table"] = "花园桌子",
    ["Garment Steamer"] = "服装蒸汽机",
    ["Gas Tube"] = "气体管",
    ["Gavel Trophy"] = "木槌奖杯",
    ["Gem"] = "宝石",
    ["General"] = "常规",
    ["Get / Claim Now"] = "立即获取/领取",
    ["Giant Pearl"] = "巨大珍珠",
    ["Glass Wave Souvenir"] = "玻璃波纹纪念品",
    ["Gold"] = "金色",
    ["Golf Car"] = "高尔夫车",
    ["GPS"] = "全球定位系统",
    ["Grab Lost & Found First"] = "优先拿失物招领",
    ["Grade Priority"] = "评级优先级",
    ["Grade: Max Item Value ($, 0 = no limit)"] = "评级：最高物品价值 ($, 0 = 无限制)",
    ["Grade: Min Item Value ($)"] = "评级：最低物品价值 ($)",
    ["Grade: Min Rarity"] = "评级：最低稀有度",
    ["Grade: Only Categories (empty = all)"] = "评级：仅类别（空 = 全部）",
    ["Grade: Only Items (empty = all)"] = "评级：仅物品（空 = 全部）",
    ["Grade: Only Mutations (empty = all)"] = "评级：仅变异（空 = 全部）",
    ["Grade: Skip Categories"] = "评级：跳过类别",
    ["Grades to Send (empty = all)"] = "要发送的等级（空 = 全部）",
    ["Grain Scoop"] = "谷物勺子",
    ["Grape"] = "葡萄",
    ["Gravel Path"] = "碎石路",
    ["Green House"] = "绿色房屋",
    ["Green Radiant Bench"] = "绿色辐射长椅",
    ["Ground Master Spoiler"] = "地面大师扰流板",
    ["Ground Placement"] = "地面放置",
    ["GT Wing"] = "GT 翅膀",
    ["Guppy Fish"] = "孔雀鱼",
    ["Half Wall Fence"] = "半墙围栏",
    ["Hammer"] = "锤子",
    ["Hammock"] = "吊床",
    ["Hand Blender"] = "手持搅拌机",
    ["Hand Compass"] = "手动指南针",
    ["Hand Grenade"] = "手榴弹",
    ["Hand Saw"] = "手锯",
    ["Hand Truck"] = "手推车",
    ["Handgun"] = "手枪",
    ["Handphone"] = "手机",
    ["Handycam"] = "手持摄像机",
    ["Hanging Pot"] = "悬挂锅",
    ["Harvesting Knife"] = "收获刀",
    ["Harvesting Tool"] = "收获工具",
    ["Hay"] = "干草",
    ["Hay Baller"] = "干草球制造者",
    ["Hazard Sign"] = "危险标志",
    ["Herbs Planter"] = "草药种植者",
    ["Hide Car (Body Noclip)"] = "隐藏汽车（车身穿墙）",
    ["Hide Stock Placement Notifications"] = "隐藏补货放置通知",
    ["Highest value"] = "最高价值",
    ["Hoe"] = "锄头",
    ["Hologram"] = "全息",
    ["Horse"] = "马",
    ["Horseshoe"] = "马蹄铁",
    ["How do I get help or updates?"] = "如何获取帮助或更新？",
    ["How do I import / export configs?"] = "如何导入/导出配置？",
    ["How do I make suggestions?"] = "如何提出建议？",
    ["How do I report bugs?"] = "如何报告错误？",
    ["Huge"] = "巨大",
    ["Hydraulic Press"] = "液压机",
    ["Hydroponic Planter"] = "水培花盆",
    ["Ice Cream Showcase"] = "冰淇淋展示柜",
    ["Ice Cube Tray"] = "冰块托盘",
    ["Ignore Favorited Items Everywhere"] = "到处忽略收藏物品",
    ["Import Config from Clipboard Text"] = "从剪贴板文本导入配置",
    ["Include Cargo Ship Event"] = "包含货船事件",
    ["Included in this hub"] = "包含在此中心中",
    ["Index"] = "图鉴",
    ["Index / Collections"] = "图鉴 / 收藏",
    ["Index Status"] = "图鉴状态",
    ["Index to complete"] = "要完成的图鉴",
    ["Indoor Stone Decoration"] = "室内石头装饰",
    ["Industrial Cable Roll"] = "工业电缆卷",
    ["Industrial Robot Arm"] = "工业机器人手臂",
    ["Industrial Scale"] = "工业规模",
    ["Infinite Jump"] = "无限跳跃",
    ["INFINITE YIELD"] = "无限收益",
    ["Inflatable Boat"] = "充气船",
    ["Inflatable Motorboat"] = "充气摩托艇",
    ["Info"] = "信息",
    ["Instant Collect (No Wind-Up)"] = "即时收集（无蓄力）",
    ["Inventory Types To Place"] = "要放置的库存类型",
    ["Invisible containers are controlled in Utilities > Optimization."] = "隐形容器在 工具 > 优化 中控制。",
    ["Irrigation Path"] = "灌溉路",
    ["Items Per Placement Pass"] = "每次放置物品数",
    ["Items Per Restock"] = "每次补货物品数",
    ["Items to Favourite"] = "要收藏的物品",
    ["Items to Send (empty = all)"] = "要发送的物品（空 = 全部）",
    ["Items To Store"] = "要存储的物品",
    ["Jade Bracelet"] = "翡翠手镯",
    ["Jellyfish Plushy"] = "水母毛绒玩具",
    ["Jellyfish Wristband"] = "水母腕带",
    ["Jet Turbine"] = "喷气式涡轮机",
    ["Jetski"] = "喷气滑水车",
    ["Join Discord for Keyless Scripts"] = "加入 Discord 获取无密钥脚本",
    ["Join Discord to Make Money"] = "加入 Discord 赚钱",
    ["Join the Discord and drop it in suggestions, most of them get added."] = "加入 Discord 并在建议频道发布，大多数会被添加。",
    ["Join the Discord and post it in the bugs channel."] = "加入 Discord 并在错误频道发帖。",
    ["Join the Discord, updates and support are posted there first."] = "加入 Discord，更新和支持会首先发布在那里。",
    ["Jukebox"] = "点唱机",
    ["Jump Power"] = "跳跃力",
    ["Jump Power Value"] = "跳跃力值",
    ["Junk"] = "垃圾",
    ["Junk Safe"] = "垃圾保险箱",
    ["Junk Yard"] = "垃圾场",
    ["Jurassic"] = "侏罗纪",
    ["Kalimba"] = "卡林巴",
    ["Keep Copies In Inventory"] = "在库存中保留副本",
    ["Keep Exact Drink Stock Targets"] = "保持精确饮料库存目标",
    ["Keep Items By Value"] = "按价值保留物品",
    ["Keep Value Threshold ($)"] = "保留价值阈值 ($)",
    ["Key"] = "钥匙",
    ["Keyless Ends in 1 Day, Join Discord Server"] = "无密钥将在1天后结束，加入 Discord 服务器",
    ["Kick"] = "踢",
    ["King Frog"] = "青蛙之王",
    ["Kite"] = "风筝",
    ["Knife"] = "小刀",
    ["Koi Fish"] = "锦鲤鱼",
    ["Ladder"] = "梯子",
    ["Lantern"] = "灯笼",
    ["Laughing Beach Totem"] = "欢笑海滩图腾",
    ["Lava Lamp"] = "熔岩灯",
    ["Lawn Mower"] = "割草机",
    ["Leather Back Pack"] = "皮革背包",
    ["Leave Delay"] = "离开延迟",
    ["Leave If Bid Over Max"] = "如果出价超过最高则离开",
    ["Leave If Bid Under Min"] = "如果出价低于最低则离开",
    ["Leave If Lot Under Value"] = "如果拍品价值低于则离开",
    ["LED Flashlight"] = "LED手电筒",
    ["Life Ring"] = "救生圈",
    ["Lighter"] = "打火机",
    ["Lighthouse Decoration"] = "灯塔装饰",
    ["Limited"] = "有限的",
    ["Live Status Updates"] = "实时状态更新",
    ["Livestock"] = "牲畜",
    ["Livestock Handbrush"] = "牲畜手刷",
    ["Living Room Stand Lamp"] = "客厅落地灯",
    ["Llama"] = "骆驼",
    ["Load config"] = "加载配置",
    ["Load theme"] = "加载主题",
    ["Lock"] = "锁定",
    ["Log"] = "日志",
    ["Longtail Drag Boat"] = "长尾拖船",
    ["Loot"] = "战利品",
    ["Loot Minimum Rarity"] = "最低拾取稀有度",
    ["Loot Only These Items"] = "只拾取这些物品",
    ["Loot Range (studs)"] = "拾取范围 (studs)",
    ["Lost"] = "丢失",
    ["Lost & Found Minimum Rarity"] = "失物招领最低稀有度",
    ["Lost Item ESP"] = "失物 ESP",
    ["Lowline Wing"] = "低线翅膀",
    ["Luck Drink 1"] = "幸运饮料 1",
    ["Luck Drink 1 Target Stock (0 = don't buy)"] = "幸运饮料1目标库存（0 = 不买）",
    ["Luck Drink 2"] = "幸运饮料 2",
    ["Luck Drink 2 Target Stock (0 = don't buy)"] = "幸运饮料2目标库存（0 = 不买）",
    ["Luck Drink 3"] = "幸运饮料 3",
    ["Luck Drink 3 Target Stock (0 = don't buy)"] = "幸运饮料3目标库存（0 = 不买）",
    ["Lucky Beach"] = "幸运海滩",
    ["Luxury Watch"] = "豪华手表",
    ["Mail Box"] = "邮箱",
    ["Main color"] = "主颜色",
    ["Make N Navigation Buttons Teleport"] = "使 N 导航按钮传送",
    ["Management"] = "管理",
    ["Manta Spoiler"] = "曼塔扰流板",
    ["Marble Plate"] = "大理石板",
    ["Marble Vase"] = "大理石花瓶",
    ["Match all filters"] = "匹配所有过滤器",
    ["Mattock"] = "巨锄",
    ["Mattress"] = "床垫",
    ["Max Bid ($, 0 = no limit)"] = "最高出价 ($, 0 = 无限制)",
    ["Max Copies Per Item (0 = Unlimited)"] = "每物品最大副本（0 = 无限）",
    ["Max Diamonds Per Buy"] = "每次购买最大钻石",
    ["Max Sell Value ($, 0 = no limit)"] = "最高出售价值 ($, 0 = 无限制)",
    ["Max Stock Value ($)"] = "最高补货价值 ($)",
    ["Maximum Auction Walk Distance"] = "最大拍卖行走距离",
    ["Maximum Item Value ($, 0 = no limit)"] = "最高物品价值 ($, 0 = 无限制)",
    ["Menu"] = "菜单",
    ["Mermaid Statue"] = "美人鱼雕像",
    ["Message in Bottle"] = "瓶子里的信息",
    ["Metal Safe"] = "金属保险箱",
    ["Microwave"] = "微波炉",
    ["Milk Can"] = "牛奶罐",
    ["Min Bid ($)"] = "最低出价 ($)",
    ["Min Item Value to Send ($, 0 = all)"] = "发送的最低物品价值 ($, 0 = 全部)",
    ["Min Lot Value ($)"] = "最低拍品价值 ($)",
    ["Min Sell Rate (%)"] = "最低出售率 (%)",
    ["Min Winnings Condition (%, 0 = all)"] = "最低收益条件 (%, 0 = 全部)",
    ["Mini Storage Box"] = "迷你储物箱",
    ["Minimum Diamonds To Keep"] = "最低保留钻石",
    ["Minimum Item Value ($)"] = "最低物品价值 ($)",
    ["Minimum Lost & Found Value ($)"] = "最低失物招领价值 ($)",
    ["Minimum Offer % Above Base"] = "最低报价高于基础 %",
    ["Minimum Offer Value ($)"] = "最低报价价值 ($)",
    ["Minimum Placement Spacing"] = "最小放置间距",
    ["Minimum Sell Value ($)"] = "最低出售价值 ($)",
    ["Minimum Stat Value"] = "最低属性值",
    ["Minimum Stock Value ($)"] = "最低补货价值 ($)",
    ["Minimum Winnings Value ($)"] = "最低收益价值 ($)",
    ["Mint"] = "全新",
    ["Misc"] = "杂项",
    ["Misc Utilities"] = "杂项工具",
    ["Moai Statue"] = "莫艾雕像",
    ["Modern Chair"] = "现代椅子",
    ["Molotov Cocktail"] = "燃烧瓶",
    ["Money Counter"] = "货币计数器",
    ["Monochrome (default)"] = "单色（默认）",
    ["Moonlit"] = "月光照耀下",
    ["Mooring Buoy"] = "系泊浮标",
    ["Mooring Post"] = "系泊柱",
    ["Mooring Winch"] = "系泊绞盘",
    ["Moped"] = "摩托车",
    ["Moped Rear View Mirror"] = "摩托车后视镜",
    ["Mosquito Trap"] = "捕虫陷阱",
    ["Moss Terrarium"] = "苔藓玻璃柜",
    ["Motorbike Helmet"] = "摩托车头盔",
    ["Mouse Trap"] = "老鼠陷阱",
    ["Movement"] = "移动",
    ["MP3 Player"] = "MP3 玩家",
    ["Multivision Goggles"] = "多视觉护目镜",
    ["Mutation Match"] = "变异匹配",
    ["Mutation Rule"] = "变异规则",
    ["Mutations to Favourite"] = "要收藏的变异",
    ["Needle"] = "针",
    ["Neon Shop Sign"] = "霓虹商店标志",
    ["Network"] = "网络",
    ["Never Sell Categories"] = "永不出售类别",
    ["Never Sell Grades"] = "永不出售等级",
    ["Never Sell Items"] = "永不出售物品",
    ["Never Sell Mutations"] = "永不出售变异",
    ["Never Stock Categories (Always Excluded)"] = "永不补货类别（总是排除）",
    ["Never Stock Items (Always Excluded)"] = "永不补货物品（总是排除）",
    ["Newspaper Rack"] = "报纸架",
    ["Nitro Tube"] = "氮气管",
    ["Noble Vampire Top Hat"] = "高贵吸血鬼礼帽",
    ["Noclip"] = "穿墙",
    ["Notify At Value ($)"] = "在价值通知 ($)",
    ["Nuclear Bunker Entrance"] = "核弹掩体入口",
    ["Nuclear Sign"] = "核标志",
    ["Ocean Buoy"] = "海洋浮标",
    ["Oil Press"] = "榨油机",
    ["Old TV"] = "老式电视机",
    ["Onion"] = "洋葱",
    ["Only Rarities (empty = all)"] = "仅稀有度（空 = 全部）",
    ["Only Sell At Good Quick Sell Rate"] = "仅在良好快速出售率时出售",
    ["Only Sell Categories (empty = all)"] = "仅出售类别（空 = 全部）",
    ["Only Sell Rarities"] = "仅出售稀有度",
    ["Optimization"] = "优化",
    ["Orange Seeds"] = "橙子种子",
    ["Orange Tree"] = "橙子树",
    ["Other"] = "其他",
    ["Other Upgrades"] = "其他升级",
    ["Ouroboros Hub"] = "Ouroboros 中心",
    ["Outdoor AC"] = "室外空调",
    ["Outdoor Changing Room"] = "户外更衣室",
    ["Outdoor Umbrella Table"] = "户外雨伞桌",
    ["Outline color"] = "轮廓颜色",
    ["Overwrite config"] = "覆盖配置",
    ["Overwrite theme"] = "覆盖主题",
    ["Painting"] = "绘画",
    ["Paper Bag"] = "纸袋",
    ["Parmesan Cheese"] = "帕尔马奶酪",
    ["Part Mutations"] = "零件变异",
    ["Party Hat"] = "派对帽",
    ["Paste exported config here"] = "在此粘贴导出的配置",
    ["Patched Rag Slime"] = "补丁碎布粘液",
    ["PC"] = "电脑",
    ["Pearl"] = "珍珠",
    ["Pedal Boat"] = "踏板船",
    ["Pencil Sharpener"] = "铅笔削尖器",
    ["Pendant Lamp"] = "吊灯",
    ["Pendulum"] = "摆钟",
    ["Performance"] = "性能",
    ["Pergola"] = "凉亭",
    ["Pesticide Sprayer"] = "农药喷雾器",
    ["Pet Bath Tub"] = "宠物浴缸",
    ["Pet Bed"] = "宠物床",
    ["Petroglyphs Backpack"] = "岩画背包",
    ["Petrol Container"] = "汽油容器",
    ["Petrol Pump"] = "汽油泵",
    ["Pickle Jar"] = "泡菜罐",
    ["Pig"] = "猪",
    ["Piglet"] = "小猪",
    ["Pigsty"] = "猪圈",
    ["Pillow"] = "枕头",
    ["Pineapple"] = "菠萝",
    ["Pink LED Stripe"] = "粉色LED条纹",
    ["Pipe"] = "管子",
    ["Piranha Fish"] = "食人鱼",
    ["Pizza Slice"] = "披萨片",
    ["Place 50% more items on your plot before hitting the build limit."] = "在达到建造上限之前，在你的地块上放置50%更多的物品。",
    ["Place 50% more shelves and displays to sell more items at once."] = "增加50%的货架和展示柜，一次性出售更多物品。",
    ["Place one extra Gavel Trophy beyond your current capacity, up to 4 when fully upgraded."] = "在当前容量之外再放置一个木槌奖杯，最多可在完全升级时放置4个。",
    ["Place selected"] = "放置选中的",
    ["Placement Point X"] = "放置点 X",
    ["Placement Point Z"] = "放置点 Z",
    ["Plane Slime"] = "飞机粘液",
    ["Plant"] = "植物",
    ["Plant Fence"] = "植物栅栏",
    ["Plant on Podium"] = "在领奖台上种植植物",
    ["Plant Pot"] = "花盆",
    ["Plastic Ball"] = "塑料球",
    ["Plastic Basket"] = "塑料篮子",
    ["Plastic Bathtub"] = "塑料浴缸",
    ["Plastic Sealer"] = "塑料封口机",
    ["Player"] = "玩家",
    ["Polo Stick"] = "马球棍",
    ["Porch"] = "门廊",
    ["Portable Air Compressor"] = "便携式空气压缩机",
    ["Portable Diving Oxygen"] = "便携式潜水氧气",
    ["Portable Drill"] = "便携式钻头",
    ["Portable Game Console"] = "便携式游戏控制台",
    ["Portable Generator"] = "便携式发电机",
    ["Post Pole Digger"] = "柱杆挖掘者",
    ["Potato"] = "土豆",
    ["Power Plant"] = "发电厂",
    ["Power Plant Parts"] = "发电厂零件",
    ["Powers"] = "能力",
    ["Powers To Buy"] = "要购买的能力",
    ["Prefer Best Garage"] = "优先最佳车库",
    ["Preferred Rods"] = "偏好鱼竿",
    ["Prehistoric Car"] = "史前汽车",
    ["Pressure Cooker"] = "压力锅",
    ["PriceTags"] = "价格标签",
    ["Printer"] = "打印机",
    ["Prioritize Vaults, Luck Drinks, Certificates & Authenticated Accessories"] = "优先金库、幸运饮料、证书和认证配件",
    ["Private Jet"] = "私人喷气机",
    ["Processing"] = "处理",
    ["Processing / Repair"] = "处理 / 修理",
    ["Professional Camera"] = "专业摄像头",
    ["Projector Screen"] = "投影仪屏幕",
    ["Propane Tank"] = "丙烷罐",
    ["Puffer Fish Plushy"] = "河豚毛绒玩具",
    ["Pumpkin Plant"] = "南瓜植物",
    ["Purchases"] = "购买",
    ["Pure"] = "纯净",
    ["Quantum Computer"] = "量子计算机",
    ["Quest"] = "任务",
    ["Quest Debug Logging"] = "任务调试日志",
    ["Quest NPCs (empty = all)"] = "任务 NPC（空 = 全部）",
    ["Quest Task Types (empty = all)"] = "任务类型（空 = 全部）",
    ["Quests"] = "任务",
    ["Race Car Dominus"] = "赛车多米纳斯",
    ["Race Trophy"] = "比赛奖杯",
    ["Race Valk"] = "竞速瓦尔克",
    ["Racing Boat"] = "赛艇",
    ["Radar Monitor"] = "雷达监控器",
    ["Radiation Monitoring Screen"] = "辐射监控屏幕",
    ["Rainbow"] = "彩虹",
    ["Rainbow Paintings"] = "彩虹画作",
    ["Rake"] = "耙子",
    ["RAM"] = "随机存取存储器",
    ["Ram"] = "公羊",
    ["Randomise"] = "随机",
    ["Rare"] = "稀有",
    ["Rare Find Notifier"] = "稀有发现通知",
    ["Rarities To Place"] = "要放置的稀有度",
    ["Rarity (Highest First)"] = "稀有度（最高优先）",
    ["Rattan Heart Arch"] = "藤制心形拱门",
    ["Razor Spoiler"] = "剃刀扰流板",
    ["RC Car"] = "遥控车",
    ["Red Crystal"] = "红色水晶",
    ["Reel Method"] = "收线方法",
    ["Refresh list"] = "刷新列表",
    ["Refresh Status"] = "刷新状态",
    ["Refresh Vehicles"] = "刷新车辆",
    ["Refresh Waypoints"] = "刷新路径点",
    ["Repair: Min Item Value ($)"] = "修理：最低物品价值 ($)",
    ["Repair: Min Rarity"] = "修理：最低稀有度",
    ["Requests get taken seriously. A lot of what is in this script started as a Discord message."] = "请求会被认真对待。这个脚本中的很多内容都始于 Discord 消息。",
    ["Rescue Board"] = "救援板",
    ["Reset autoload"] = "重置自动加载",
    ["Reset default"] = "重置默认",
    ["Reset Point To Plot Center"] = "重置点到地块中心",
    ["Restaurant Sofa"] = "餐厅沙发",
    ["Restock Every"] = "每隔补货",
    ["Rewards"] = "奖励",
    ["Rice Cooker"] = "电饭锅",
    ["Rider Helmet"] = "骑手头盔",
    ["RightShift"] = "右 Shift",
    ["Ripped Certificate Of Authenticity"] = "破损的真品证明书",
    ["Road Cone"] = "道路锥",
    ["Robot Vacuum"] = "机器人吸尘器",
    ["Rods"] = "鱼竿",
    ["Rolled Tip"] = "滚动尖端",
    ["Roof Sheet"] = "屋顶板",
    ["Roof Shingles"] = "屋顶瓦片",
    ["Room Heater"] = "房间加热器",
    ["Room Separator"] = "房间隔板",
    ["Rope Bracelet"] = "绳索手镯",
    ["Rope Ladder"] = "绳梯",
    ["Rubber Duck"] = "橡皮鸭",
    ["Rubik's Cube"] = "魔方",
    ["Rusty Lock"] = "生锈的锁",
    ["Saddle"] = "马鞍",
    ["Safe ESP"] = "保险箱 ESP",
    ["Safe Wristband"] = "安全腕带",
    ["Safes"] = "保险箱",
    ["Safes & Lockpicks"] = "保险箱与开锁工具",
    ["Safety Helmet"] = "安全头盔",
    ["Sailor Bag"] = "水手包",
    ["Sailor Hat"] = "水手帽",
    ["Salmon Fish"] = "三文鱼",
    ["Sand Dollar"] = "沙币",
    ["Sandwich Maker"] = "三明治制作者",
    ["Sandy"] = "沙质",
    ["Satellite Dish"] = "卫星天线",
    ["Scanner - Conveyor Belt"] = "扫描仪 - 传送带",
    ["Scarecrow"] = "稻草人",
    ["Scientist Bed"] = "科学家床",
    ["Scientist Chair"] = "科学家椅子",
    ["Scissors"] = "剪刀",
    ["Scooter"] = "滑板车",
    ["Scrap Dominus"] = "废料多米纳斯",
    ["Scrap Fishing Rod"] = "废旧钓鱼竿",
    ["Scrap Valk"] = "废料瓦尔克",
    ["Screwdriver"] = "螺丝刀",
    ["Scripts"] = "脚本",
    ["Scythe"] = "镰刀",
    ["Sea Mine"] = "海洋矿",
    ["Seal Plushy"] = "海豹毛绒玩具",
    ["Search..."] = "搜索...",
    ["Secret"] = "秘密",
    ["Security CCTV Monitor"] = "安全监控器",
    ["Security Metal Detector"] = "安检金属探测器",
    ["Seedling Tray"] = "育苗托盘",
    ["Select All"] = "全选",
    ["Self Balancing Board"] = "自平衡板",
    ["Self Balancing Scooter"] = "自动平衡滑板车",
    ["Sell Method"] = "出售方法",
    ["Selling"] = "出售",
    ["Send Auction Winnings Claimed"] = "发送拍卖收益已领取",
    ["Send Grading Results"] = "发送评级结果",
    ["Send Net Worth Now"] = "立即发送净资产",
    ["Send Webhook Alerts"] = "发送 Webhook 警报",
    ["Set as autoload"] = "设为自动加载",
    ["Set as default"] = "设为默认",
    ["Set Placement Point To My Position"] = "将放置点设为我的位置",
    ["Settings"] = "设置",
    ["Settings > Export Config copies your settings to the clipboard. Paste that text into the import box and press Import."] = "设置 > 导出配置 会将你的设置复制到剪贴板。将该文本粘贴到导入框并按导入。",
    ["Shape Toy"] = "形状玩具",
    ["Sheep"] = "羊",
    ["Shelf Price (% of Value)"] = "货架价格（价值的 %）",
    ["Shelf Stocking"] = "货架补货",
    ["Ship Anchor"] = "船舶锚固装置",
    ["Ship Compass"] = "船舶指南针",
    ["Ship Horn"] = "船用喇叭",
    ["Ship Porthole"] = "船舶舷窗",
    ["Ship Propeller"] = "船舶螺旋桨",
    ["Ship Satellite Dome"] = "船舶卫星穹顶",
    ["Ship Spotlight"] = "船舶聚光灯",
    ["Shipyard"] = "造船厂",
    ["Shirt"] = "衬衫",
    ["Shocked"] = "感电",
    ["Shoe Rack"] = "鞋架",
    ["Shooting Target"] = "射击目标",
    ["Shop / NPC ESP"] = "商店 / NPC ESP",
    ["Shop Expansion"] = "商店扩展",
    ["Shop Metal Detector"] = "商店金属探测器",
    ["Shop Sign Board"] = "商店标志牌",
    ["Shovel"] = "铲子",
    ["Showcased"] = "展示",
    ["Shower Tub"] = "淋浴浴缸",
    ["Side Speaker"] = "侧面扬声器",
    ["Silver"] = "白银",
    ["Single Tip"] = "单个提示",
    ["Ski Mask"] = "滑雪面具",
    ["Skip Equipped Accessories"] = "跳过已装备配件",
    ["Skip Favorited Accessories"] = "跳过已收藏配件",
    ["Skip Fishing Animation"] = "跳过钓鱼动画",
    ["Skip items over 1 in X (0 = no skip)"] = "跳过超过 1/X 的物品（0 = 不跳过）",
    ["Skip selected mutations"] = "跳过选中的变异",
    ["Skull Domino Crown"] = "骷髅多米诺皇冠",
    ["Slant Single"] = "斜坡单人座椅",
    ["Sledge Hammer"] = "大锤",
    ["Slip the mechanic a tip for free vehicle customisation."] = "给机械师小费，以获得免费的车辆定制服务。",
    ["Slippers"] = "拖鞋",
    ["Slots"] = "槽位",
    ["Small City Car"] = "小城市汽车",
    ["Small Electricity Transformer"] = "小型电力变压器",
    ["Small Fridge"] = "小冰箱",
    ["Smart (track zone)"] = "智能（跟踪区域）",
    ["SMG"] = "冲锋枪",
    ["Smoke Grenade"] = "烟雾弹",
    ["Sniper Rifle"] = "狙击步枪",
    ["Snorkeling Goggles"] = "潜水镜",
    ["Socials"] = "社交",
    ["Sofa"] = "沙发",
    ["Solar Panel"] = "太阳能电池板",
    ["Spawn Vehicle"] = "生成车辆",
    ["Specific Items To Place"] = "要放置的特定物品",
    ["Speed Limit Sign"] = "速度限制标志",
    ["Speed Up Fishing"] = "加速钓鱼",
    ["Speed Up Safes (Diamonds)"] = "加速保险箱（钻石）",
    ["Spike Wristband"] = "尖刺腕带",
    ["Spilled Nuclear Waste"] = "泄漏的核废料",
    ["Spin Top"] = "旋转顶部",
    ["Spoon"] = "勺子",
    ["Sport Car Rims"] = "跑车轮圈",
    ["Sport Motorbike"] = "运动摩托车",
    ["Spotless"] = "无瑕",
    ["Spray Paint"] = "喷漆",
    ["Square Ceiling Lamp"] = "方形吸顶灯",
    ["Stack Firewood"] = "堆放柴火",
    ["Stack Log"] = "堆叠日志",
    ["Stack Pot Planter"] = "堆叠罐栽种植物",
    ["Stacked Dice Decoration"] = "堆叠的骰子装饰",
    ["Stand Speaker"] = "立式扬声器",
    ["Stand Webcam"] = "支架摄像头",
    ["Standing Punching Bag"] = "立式沙袋",
    ["Star Decoration"] = "星星装饰",
    ["Starfish"] = "海星",
    ["Starfish Lamp"] = "海星灯",
    ["Start At Inventory Fullness"] = "在库存满度时开始",
    ["Start Auctions Below Inventory %"] = "库存低于 % 时开始拍卖",
    ["Stat Categories (empty = all)"] = "属性类别（空 = 全部）",
    ["Stat Rarities (empty = all)"] = "属性稀有度（空 = 全部）",
    ["Stats To Favorite"] = "要收藏的属性",
    ["Status"] = "状态",
    ["Stay on Plot For Stocking Items"] = "补货物品时留在地块",
    ["Steel Pan Instrument"] = "钢锅乐器",
    ["Steel Storage Box"] = "钢制储物箱",
    ["Stepped Wing"] = "阶梯翅膀",
    ["Stock Categories"] = "补货类别",
    ["Stock Grades"] = "补货等级",
    ["Stock Items"] = "补货物品",
    ["Stock Mutations"] = "补货变异",
    ["Stock Priority"] = "补货优先级",
    ["Stock Rarities"] = "补货稀有度",
    ["Stone"] = "石头",
    ["Stone Double Sofa"] = "石质双人沙发",
    ["Stone Fence"] = "石栅栏",
    ["Stone Gate Sign"] = "石质大门标志",
    ["Stone Single Sofa"] = "石质单人沙发",
    ["Stone Table"] = "石桌",
    ["Stop All Automation"] = "停止所有自动化",
    ["Stop NPC Bid"] = "停止 NPC 出价",
    ["Stop NPC Bid Mode"] = "停止 NPC 出价模式",
    ["Stop Sign"] = "停止标志",
    ["Storage Boxes"] = "储物箱",
    ["Storage Hunters"] = "仓储猎人",
    ["Storage Server"] = "存储服务器",
    ["Storage Shelves"] = "存储架",
    ["StorageBoxCapacity"] = "储物箱容量",
    ["Straight Vent Pipe"] = "直通通风管",
    ["Strange Egg"] = "奇怪的蛋",
    ["Straw Hat"] = "草帽",
    ["Street Lamp"] = "路灯",
    ["Structure"] = "结构",
    ["Subwoofer"] = "低音扬声器",
    ["Suitcase"] = "行李箱",
    ["Sun Lounger"] = "太阳躺椅",
    ["Sunflower Plant"] = "向日葵盆栽",
    ["Sunflower Seeds"] = "向日葵种子",
    ["Sunset Painting"] = "日落画作",
    ["Supercharger"] = "超级充电器",
    ["Surf Board"] = "冲浪板",
    ["Surf Shop Sign"] = "冲浪店标志",
    ["Table Lamp"] = "台灯",
    ["Tablet"] = "平板电脑",
    ["Targets: --"] = "目标: --",
    ["Teak Wood Bed"] = "柚木床",
    ["Teak Wood Bed Couch"] = "柚木床沙发",
    ["Teak Wood Chair"] = "柚木椅子",
    ["Teak Wood Double Sofa"] = "柚木双人沙发",
    ["Teak Wood Single Sofa"] = "柚木单人沙发",
    ["Teak Wood Table"] = "柚木桌",
    ["Teleport"] = "传送",
    ["Tennis Ball"] = "网球",
    ["Tesla Coil"] = "特斯拉线圈",
    ["The Discord has ready made configs, dupe methods, giveaways, and early access to new scripts."] = "Discord 有现成的配置、复制方法、抽奖和新脚本的早期访问。",
    ["The Drifter"] = "流浪者",
    ["The Mini"] = "迷你",
    ["The Sleeper"] = "沉睡者",
    ["Theme list"] = "主题列表",
    ["Themes"] = "主题",
    ["Threshold Bypass"] = "阈值绕过",
    ["Timeless"] = "永恒",
    ["Tin Bin"] = "锡罐",
    ["Tiny"] = "微小",
    ["TipJar"] = "小费罐",
    ["Tissue Box"] = "纸巾盒",
    ["Toggle"] = "切换",
    ["Toilet Paper"] = "卫生纸",
    ["Toilet Plunger"] = "马桶疏通器",
    ["Tomato Plant"] = "番茄植物",
    ["Tomato Seeds"] = "番茄种子",
    ["Tool"] = "工具",
    ["Torch"] = "火把",
    ["Torned Fedora"] = "破损的费多拉帽",
    ["Towing Car"] = "拖车",
    ["Toy Car"] = "玩具车",
    ["Toy Spider"] = "玩具蜘蛛",
    ["Tractor Tire"] = "拖拉机轮胎",
    ["Tractor Wheel Stack"] = "拖拉车轮堆",
    ["Treadmill"] = "跑步机",
    ["Tree Stump"] = "树桩",
    ["Triceratops"] = "三角龙",
    ["Tricycle"] = "三轮车",
    ["Trophy"] = "奖杯",
    ["Trophy Rule Items"] = "奖杯规则物品",
    ["Trophy Rule Mutation Match"] = "奖杯规则变异匹配",
    ["Trophy Rule Mutations"] = "奖杯规则变异",
    ["TrophyCapacity"] = "奖杯容量",
    ["Tropical Shade"] = "热带阴影",
    ["Tuna Fish"] = "金枪鱼",
    ["Tuning Fork"] = "调音叉",
    ["Turbo"] = "涡轮增压",
    ["Turntable"] = "转盘",
    ["Turtle Fedora"] = "海龟礼帽",
    ["TV Table"] = "电视桌",
    ["UI Keybind"] = "UI 快捷键",
    ["Umbrella"] = "雨伞",
    ["Uncommon"] = "罕见",
    ["Unload"] = "卸载",
    ["Unload at %"] = "在 % 卸载",
    ["Unload every 20s"] = "每20秒卸载",
    ["Unload Method"] = "卸载方法",
    ["Unload Truck At % Full"] = "卡车满 % 时卸载",
    ["Unload when Full"] = "满时卸载",
    ["Use a fully supported executor for every feature."] = "使用完全支持的执行器以获得所有功能。",
    ["Use when active runs out"] = "当生效结束时使用",
    ["Used Tire"] = "废旧轮胎",
    ["Utilities"] = "工具",
    ["Uzi"] = "乌兹冲锋枪",
    ["Vacuum Cleaner"] = "吸尘器",
    ["Value (Highest First)"] = "价值（最高优先）",
    ["Vampire Bat Valk"] = "吸血蝙蝠瓦尔克",
    ["Vampire Chair"] = "吸血鬼椅子",
    ["Vehicle"] = "车辆",
    ["Vehicle Parts"] = "车辆零件",
    ["Vending Machine"] = "自动贩卖机",
    ["Vertical Wind Turbine"] = "垂直风力涡轮机",
    ["Vine Exhaust"] = "藤蔓排气",
    ["Void"] = "虚空",
    ["Volcano Humidifier"] = "火山加湿器",
    ["Volleyball Net"] = "排球网",
    ["VR Goggles"] = "虚拟现实护目镜",
    ["Wagon Wheel Stack"] = "车轮堆",
    ["Wait Until Inventory Below %"] = "等待直到库存低于 %",
    ["Walk Speed"] = "行走速度",
    ["Walk Speed Value"] = "行走速度值",
    ["Walk to Nearby Auctions"] = "走向附近的拍卖",
    ["Walkie Talkie"] = "对讲机",
    ["Wall CCTV"] = "墙壁监控摄像头",
    ["Wall Clock"] = "壁挂钟",
    ["Wall Lamp"] = "壁灯",
    ["Wall Mirror"] = "壁镜",
    ["Warning Rug"] = "警告地毯",
    ["Wash: Always Include Safes"] = "清洗：总是包括保险箱",
    ["Wash: Min Item Value ($)"] = "清洗：最低物品价值 ($)",
    ["Wash: Min Rarity"] = "清洗：最低稀有度",
    ["Water Container"] = "水容器",
    ["Water Dispenser"] = "饮水机",
    ["Water Hand Pump"] = "水手动泵",
    ["Water Heater"] = "热水器",
    ["Water Sprinkler"] = "洒水器",
    ["Water Tank Trailer"] = "水箱拖车",
    ["Water Tower"] = "水塔",
    ["Watering Can"] = "洒水壶",
    ["Waypoint"] = "路径点",
    ["Weapon"] = "武器",
    ["Weather System"] = "天气系统",
    ["Weld Mask"] = "焊接面具",
    ["Welding Machine"] = "焊接机",
    ["Well"] = "井",
    ["Wet"] = "潮湿",
    ["Wheelbarrow"] = "独轮车",
    ["White LED Stripe"] = "白色LED灯条",
    ["Wild Flowers"] = "野花",
    ["Wind Chimes"] = "风铃",
    ["Windmill"] = "风车",
    ["Window Blind"] = "窗户百叶",
    ["Winnings Minimum Rarity"] = "收益最低稀有度",
    ["Wire Fence"] = "铁网围栏",
    ["WMB Elegant Car"] = "WMB 优雅的汽车",
    ["Wood Barrel"] = "木桶",
    ["Wood Tile"] = "木质地砖",
    ["Wooden Barrel Exhaust"] = "木制桶排气",
    ["Wooden Boardwalk"] = "木制步道",
    ["Wooden Boat"] = "木船",
    ["Wooden Bridge"] = "木桥",
    ["Wooden Bucket"] = "木制桶",
    ["Wooden Canoe"] = "木制独木舟",
    ["Wooden Cart"] = "木制推车",
    ["Wooden Cart Wheel"] = "木制车轮",
    ["Wooden Certificate Of Authenticity"] = "木制真品证明",
    ["Wooden Chair"] = "木质椅子",
    ["Wooden Domino Crown"] = "木制多米诺皇冠",
    ["Wooden Fence"] = "木制栅栏",
    ["Wooden Mug"] = "木制杯子",
    ["Wooden Palette"] = "木制调色板",
    ["Wooden Safe"] = "木制保险箱",
    ["Wooden Ship Wheel"] = "木制船轮",
    ["Wooden Sign"] = "木制标志牌",
    ["Wooden Staff"] = "木制法杖",
    ["Wooden Stand Sign"] = "木制支架标志",
    ["Wooden Storage Box"] = "木制储物箱",
    ["Wooden Table"] = "木桌",
    ["Wooden Water Tower"] = "木制水塔",
    ["Wool Bundle"] = "羊毛束",
    ["Wool Shearer"] = "羊毛剪刀手",
    ["World"] = "世界",
    ["Worn-out Curtain"] = "破旧的窗帘",
    ["X-Ray"] = "X射线",
    ["Xeno and Solara are unsupported. Velocity support is limited."] = "Xeno 和 Solara 不受支持。Velocity 支持有限。",
    ["XSN Sport Car"] = "XSN 运动型汽车",
    ["Yarn"] = "毛线",
    ["Yellow LED Stripe"] = "黄色LED灯条",
}

-- ===== 部分替换表（子串替换）=====
-- 请在此按 ["英文子串"] = "中文替换" 格式添加
-- 注意：会替换文本中所有匹配的子串，请谨慎使用
local PartialTranslations = {
    -- 示例: yes no 
    --["yes"] = "是",
    ["seconds"] = "秒",
}

-- ===== 选择模式（带按钮的原生通知）=====
local function AskModeWithNotification()
    local StarterGui = game:GetService("StarterGui")
    local choice = nil

    local success, err = pcall(function()
        StarterGui:SetCore("SendNotification", {
            Title = "汉化模式选择",
            Text = "请选择翻译方式",
            Button1 = "Hook模式 (快速)",
            Button2 = "普通模式 (稳定)",
            Duration = 10,
            Callback = function(clicked)
                -- 兼容两种返回值：字符串或数字索引
                if clicked == "Hook模式 (快速)" or clicked == 1 then
                    choice = true
                elseif clicked == "普通模式 (稳定)" or clicked == 2 then
                    choice = false
                end
            end
        })
    end)

    if not success then
        warn("通知发送失败，使用普通模式:", err)
        return false
    end

    local start = os.clock()
    repeat
        wait(0.1)
    until choice ~= nil or os.clock() - start > 11

    if choice == nil then
        print("未选择，默认使用普通模式")
        return false
    end
    return choice
end

local UseHookTranslation = AskModeWithNotification()
print("最终使用模式:", UseHookTranslation and "Hook" or "普通监听")

-- ===== 翻译框架（监听模式为主）=====
local Players = game:GetService("Players")
local CoreGui = game:GetService("CoreGui")
local LocalPlayer = Players.LocalPlayer
local PlayerGui = LocalPlayer:FindFirstChild("PlayerGui")

if not PlayerGui then
    warn("未找到 PlayerGui，汉化可能无法正常工作")
end

local SystemUiNames = {
    RobloxGui=true, PlayerList=true, Backpack=true, Chat=true, BubbleChat=true,
    ExperienceChat=true, TextChatService=true, TopBar=true, Topbar=true, Health=true,
    EmotesMenu=true, Chrome=true, InspectMenu=true, PurchasePrompt=true,
    ScreenshotHud=true
}

local WatchedRoots, WatchedObjects, TranslatingObjects = setmetatable({},{__mode="k"}), setmetatable({},{__mode="k"}), setmetatable({},{__mode="k"})

local function TranslateText(txt)
    if type(txt) ~= "string" or txt == "" then return txt end
    local clean = txt:gsub("<[^>]->", ""):gsub("\r", ""):gsub("^%s+", ""):gsub("%s+$", "")

    -- 1. 精确匹配（整句）
    local exact = Translations[txt] or Translations[clean]
    if exact then return exact end

    -- 2. 部分替换（子串）
    local result = txt
    for original, translated in pairs(PartialTranslations) do
        result = result:gsub(original, translated)
    end
    return result
end

local function IsSysUI(obj)
    while obj do
        if SystemUiNames[obj.Name] then return true end
        obj = obj.Parent
    end
    return false
end

local function TranslateObj(obj)
    if IsSysUI(obj) or TranslatingObjects[obj] then return end
    TranslatingObjects[obj] = true
    pcall(function()
        local nText = TranslateText(obj.Text)
        if nText ~= obj.Text then obj.Text = nText end
        local nPlace = TranslateText(obj.PlaceholderText)
        if nPlace ~= obj.PlaceholderText then obj.PlaceholderText = nPlace end
    end)
    TranslatingObjects[obj] = nil
end

local function WatchObj(obj)
    if not (obj:IsA("TextLabel") or obj:IsA("TextButton") or obj:IsA("TextBox")) then return end
    if WatchedObjects[obj] then return end
    WatchedObjects[obj] = true

    TranslateObj(obj)

    local function onPropChange()
        if not TranslatingObjects[obj] then
            delay(0.03, function() TranslateObj(obj) end)
        end
    end

    pcall(function()
        obj:GetPropertyChangedSignal("Text"):Connect(onPropChange)
        obj:GetPropertyChangedSignal("PlaceholderText"):Connect(onPropChange)
    end)
end

local function GetRoots()
    local roots = {}
    if PlayerGui then table.insert(roots, PlayerGui) end
    pcall(function() table.insert(roots, CoreGui) end)
    pcall(function()
        if gethui then
            local hui = gethui()
            if hui then table.insert(roots, hui) end
        end
    end)
    return roots
end

local function ScanAndWatch(root)
    if not root or WatchedRoots[root] then return end
    WatchedRoots[root] = true

    pcall(function()
        for _, obj in ipairs(root:GetDescendants()) do
            WatchObj(obj)
        end
        root.DescendantAdded:Connect(function(obj)
            delay(0.05, function()
                WatchObj(obj)
                pcall(function()
                    for _, c in ipairs(obj:GetDescendants()) do
                        WatchObj(c)
                    end
                end)
            end)
        end)
    end)
end

-- ===== 如果用户选择了 Hook 模式，尝试安装 =====
local hookInstalled = false
if UseHookTranslation then
    local hookSuccess, hookErr = pcall(function()
        local mt = getrawmetatable(game)
        if not mt then error("getrawmetatable 失败") end
        local oldNewIndex = mt.__newindex
        setreadonly(mt, false)
        mt.__newindex = newcclosure(function(t, k, v)
            if (k == "Text" or k == "PlaceholderText") and
               (t:IsA("TextLabel") or t:IsA("TextButton") or t:IsA("TextBox")) and
               not IsSysUI(t) then
                v = TranslateText(tostring(v))
            end
            return oldNewIndex(t, k, v)
        end)
        setreadonly(mt, true)
    end)
    if not hookSuccess then
        warn("Hook安装失败，降级为监听模式:", hookErr)
        UseHookTranslation = false
        hookInstalled = false
    else
        print("Hook模式已启用")
        hookInstalled = true
    end
else
    print("使用普通监听模式")
end

-- ===== 启动监听扫描（即使 Hook 成功也保留作为备用） =====
spawn(function()
    while true do
        for _, root in ipairs(GetRoots()) do
            ScanAndWatch(root)
            pcall(function()
                for _, obj in ipairs(root:GetDescendants()) do
                    WatchObj(obj)
                end
            end)
        end
        wait(hookInstalled and 20 or 12)
    end
end)

wait(0.5)

-- ===== 加载外部脚本 =====
local ScriptUrl = "https://raw.githubusercontent.com/joustingmatch/Ouroboros/main/loader.lua"
print("开始下载外部脚本...")

local ok, content = pcall(function()
    return game:HttpGet(ScriptUrl)
end)

if not ok then
    warn("下载失败：", content)
elseif not content or content == "" then
    warn("内容为空")
else
    print("下载成功，长度：", #content)
    local func, err = loadstring(content)
    if not func then
        warn("编译失败：", err)
    else
        print("编译成功，执行外部脚本...")
        local execOk, execErr = pcall(func)
        if not execOk then
            warn("执行失败：", execErr)
        else
            print("外部脚本执行成功")
        end
    end
end

print("[汉化] 已加载")
